export const JOB_STATUS = {
  "interview": "phỏng vấn",
  "declined": "từ chối",
  "pending": "đang chờ",
};
export const JOB_TYPE = {
  "full-time": "toàn thời gian",
  "part-time": "làm theo giờ",
  "remote": "làm từ xa",
  "internship": "thực tập sinh",
};
export const CITIES = {
  code_4: "Tỉnh Cao Bằng",
  code_6: "Tỉnh Bắc Kạn",
  code_2: "Tỉnh Hà Giang",
  code_10: "Tỉnh Lào Cai",
  code_11: "Tỉnh Điện Biên",
  code_12: "Tỉnh Lai Châu",
  code_14: "Tỉnh Sơn La",
  code_15: "Tỉnh Yên Bái",
  code_17: "Tỉnh Hoà Bình",
  code_19: "Tỉnh Thái Nguyên",
  code_1: "Thành phố Hà Nội",
  code_22: "Tỉnh Quảng Ninh",
  code_8: "Tỉnh Tuyên Quang",
  code_25: "Tỉnh Phú Thọ",
  code_26: "Tỉnh Vĩnh Phúc",
  code_27: "Tỉnh Bắc Ninh",
  code_30: "Tỉnh Hải Dương",
  code_31: "Thành phố Hải Phòng",
  code_33: "Tỉnh Hưng Yên",
  code_34: "Tỉnh Thái Bình",
  code_35: "Tỉnh Hà Nam",
  code_36: "Tỉnh Nam Định",
  code_37: "Tỉnh Ninh Bình",
  code_38: "Tỉnh Thanh Hóa",
  code_40: "Tỉnh Nghệ An",
  code_42: "Tỉnh Hà Tĩnh",
  code_44: "Tỉnh Quảng Bình",
  code_45: "Tỉnh Quảng Trị",
  code_20: "Tỉnh Lạng Sơn",
  code_48: "Thành phố Đà Nẵng",
  code_49: "Tỉnh Quảng Nam",
  code_51: "Tỉnh Quảng Ngãi",
  code_52: "Tỉnh Bình Định",
  code_54: "Tỉnh Phú Yên",
  code_56: "Tỉnh Khánh Hòa",
  code_58: "Tỉnh Ninh Thuận",
  code_62: "Tỉnh Kon Tum",
  code_60: "Tỉnh Bình Thuận",
  code_64: "Tỉnh Gia Lai",
  code_66: "Tỉnh Đắk Lắk",
  code_67: "Tỉnh Đắk Nông",
  code_68: "Tỉnh Lâm Đồng",
  code_70: "Tỉnh Bình Phước",
  code_74: "Tỉnh Bình Dương",
  code_75: "Tỉnh Đồng Nai",
  code_72: "Tỉnh Tây Ninh",
  code_24: "Tỉnh Bắc Giang",
  code_79: "Thành phố Hồ Chí Minh",
  code_80: "Tỉnh Long An",
  code_82: "Tỉnh Tiền Giang",
  code_83: "Tỉnh Bến Tre",
  code_84: "Tỉnh Trà Vinh",
  code_86: "Tỉnh Vĩnh Long",
  code_89: "Tỉnh An Giang",
  code_87: "Tỉnh Đồng Tháp",
  code_91: "Tỉnh Kiên Giang",
  code_92: "Thành phố Cần Thơ",
  code_93: "Tỉnh Hậu Giang",
  code_94: "Tỉnh Sóc Trăng",
  code_95: "Tỉnh Bạc Liêu",
  code_96: "Tỉnh Cà codeu",
  code_46: "Tỉnh Thừa Thiên Huế",
  code_77: "Tỉnh Bà Rịa - Vũng Tàu",
};
